name: CD Pipeline with OpenShift and Quay.io

on:
  push:
    branches:
      - main  # El pipeline solo se ejecuta en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: hello-world-api

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Bump Version
        id: bump_version
        run: |
          VERSION=$(bash scripts/bump_version.sh patch)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Project
        run: npm run build

      - name: Build Docker Image
        run: |
          docker build -t quay.io/${{ secrets.QUAY_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} .

      - name: Login to Quay.io
        run: echo "${{ secrets.QUAY_PASSWORD }}" | docker login quay.io -u "${{ secrets.QUAY_USERNAME }}" --password-stdin

      - name: Push Docker Image to Quay.io
        run: docker push quay.io/${{ secrets.QUAY_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Install OpenShift CLI
        run: |
          sudo curl -L https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz -o oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/oc
          oc version

      - name: Login to OpenShift
        run: |
          oc login "${{ env.OPENSHIFT_API_URL }}" --token="${{ env.OPENSHIFT_TOKEN }}" --insecure-skip-tls-verify=true

      - name: Set Kubernetes Project
        run: |
          oc new-project hello-world-api || echo "Project already exists"
          oc project hello-world-api

      - name: Apply Deployment Configuration
        run: |
          sed -i "s|quay.io/your-repo-placeholder|quay.io/${{ secrets.QUAY_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}|g" k8s/deployment.yaml
          oc apply -f k8s/deployment.yaml